config/routes.rb
Partynight::Application.routes.draw do

  devise_for :users
  devise_for :admins

  root "pages#index"
  resources :webservices
  resources :presentations
  

  match "/user/" => "users#index", via: [:get, :post]

  match "/api/companies/" => "webservices#title_companies", via: [:get, :post]

  match "/api/place/:name" => "webservices#company_nights", via: [:get, :post]
  match "/api/night/:id" => "webservices#night", via: [:get, :post]

  resources :companies do
    resources :evenings
  end

end

app/models/evening.rb
class Evening < ActiveRecord::Base

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  #upload de files
  has_attached_file :picture,
    :styles => {
      :medium => "429×500>"
    },
    :default_url => "/images/:style/missing.png",
    :url => "/picture/:class/:attachment/:id/:style/:basename.:extension",
    :path => ":rails_root/public/picture/:class/:attachment/:id/:style/:basename.:extension"


  belongs_to :company

  validates :title, presence: true
  validates :description, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  # paperclip
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  # Evening.search({
  #   filter:{
  #     terms:{'propertie.title' => ["test","test1"]}
  #   }
  # })
end

app/controllers/evenings_controller.rb
class EveningsController < ApplicationController

  before_filter :set_resources

  def index

  end
  def new
    @evening = Evening.new
  end

  def create
    @evening = Evening.new(evening_param)
    @evening.company_id = @company.id
    if @evening.save
      redirect_to  @company, flash:{ success: "La soirée #{@evening.title} à bien été crée"}
    else
      flash.now[:error]= "Certain champs n'ont pas été corectement remplir"
      render "new"

    end
  end
  def edit
  end
  def update
    if @evening.update(evening_param)
      redirect_to  @company, flash:{ success: "La soirée #{@evening.title} à bien été crée"}
    else
      flash.now[:error]= "Certain champs n'ont pas été corectement remplir"
      render "edit"
    end
  end

  def destroy
    @evening.destroy
    redirect_to @company, flash:{ success: "Soirée supprimer"}
  end

  private
  def set_resources
    @company = Company.find(params[:company_id])
    authorize! :destroy, @company
    @evening = Evening.find(params[:id]) if params[:id]
  end
  def evening_param
      params.require(:evening).permit(:title, :nb_get_in, :description, :price, :company_id, :date_start, :date_end, :picture)
  end
end

app/helpers/evenings_helper.rb
module EveningsHelper
end

app/views/evenings/_form.html.haml
= simple_form_for [@company, @evening], :html => { :multipart => true } do |f|
  .row
    .col-md-8
      = f.input :title, label: "Titre"
    .col-md-8
      = f.input :nb_get_in, label: "nombre de place"
    .col-md-8
      = f.input :price, label: "prix"
    .col-md-8
      = f.input :description, label: "description de la soirée"
    .col-md-8
      = f.input :picture, label: "Votre affiche"
    .col-md-8
      = f.input :date_start, label: "Date du début"
    .col-md-8
      = f.input :date_end, label: "date de fin"
  = f.button :submit, "Enregistrer"

app/views/evenings/edit.html.haml
%h1 Mise  à jour de la soirée

= render 'form'

-# = link_to 'Show', @company
-# '|
-# = link_to 'Back', companies_path

app/views/evenings/index.html.slim
p coucou

app/views/evenings/new.html.haml
%h1 Creation du soirée

= render 'form'

app/views/evenings/show.html.haml
= link_to 'Back', company_path(@company.id)
= link_to 'Modifier', edit_company_evening_path(@evening.company_id,@evening)
.panel.panel-primary
  .panel-heading
    %h3.panel-title
      = "#{@evening.title}"
  .panel-body
    .row
      .col-md-6
        %img.thumbnail{ src: "#{@evening.picture.url(:medium) }" }
      .col-md-6
        %p
          %strong
            Description :
        %p= "#{@evening.description}"
        %p
          %strong
            Date du début de la soirée :
          = "#{@evening.date_start.strftime("%d/%m/%Y")}"
        %p
          %strong
            Date de la fin de la soirée :
          = "#{@evening.date_end.strftime("%d/%m/%Y")}"
        %p
          %strong
            Prix :
          = "#{@evening.price}€"
        %p
          %strong
            Nombre de place :
          = "#{@evening.nb_get_in}"

app/views/evenings/update.haml
%h1 Mise à jour.

= render 'form'