config/routes.rb
Partynight::Application.routes.draw do

  devise_for :users
  devise_for :admins

  root "pages#index"
  resources :webservices
  resources :presentations
  

  match "/user/" => "users#index", via: [:get, :post]

  match "/api/companies/" => "webservices#title_companies", via: [:get, :post]

  match "/api/place/:name" => "webservices#company_nights", via: [:get, :post]
  match "/api/night/:id" => "webservices#night", via: [:get, :post]

  resources :companies do
    resources :evenings
  end

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :evenings

  def all_evenings(id)
    @evenings = Evening.where(company_id: id)
    @evenings.to_json
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :set_company, except: [:index, :new, :create, :nightIndex]
  #only: [:show, :edit, :update, :destroy]
  authorize_resource

  def index
    @companies = Company.where(admin_id: current_admin)
    @companie_name = Company.select(:name_company).where(admin_id: current_admin).distinct

    
    # @articles = Evening.search('Hip-Hop').records

  end

  def show
    @evenings = @company.evenings
  end

  def new
    @company = Company.new
  end


  def edit
  end


  def create
    @company = Company.new(company_params)

    @company.admin_id = current_admin.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end


    def company_params
      params.require(:company).permit(:name, :adresse, :city, :cp, :admin_id, :name_company)
    end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.haml
= simple_form_for @company do |f|

  .field
    = f.input :name_company, label: "Nom de la société"

  .field
    = f.input :name, label: "Nom"
  .field
    = f.input :adresse, label: "Adresse"
  .field
    = f.input :city, label: "Ville"
  .field
    = f.input :cp, label: "Code postal"
  .actions
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
'|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
= @test.inspect

.jumbotron
  .page-header
    - @companie_name.each do |name|
      %h1= name.name_company



%p= link_to 'New Company', new_company_path, class:"btn btn-primary", role:"button"

%table.table
  %thead
    %tr
      %th Lieux
      %th Adresse
      %th Ville
      %th Code postal
      %th Actions

  %tbody
    - @companies.each do |company|
      %tr
        %td= link_to "#{company.name}", edit_company_path(company)

        %td
          = company.adresse
        %td
          = company.city
        %td
          = company.cp
        %td
          = link_to 'Show', company, class:"btn btn-primary", role:"button"
          = link_to 'Destroy', company, data: {:confirm => 'Are you sure?'}, :method => :delete, class:"btn alert-danger"



-# %div
-#   - @articles.each do |n|
-#     %p= n.title

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p= link_to "Creation d'une soirée", new_company_evening_url(@company), class:"btn btn-info", role:"button"

.row
  .col-md-4
    .page-header
      %h1= @company.name_company

    %p
      %strong Lieux:
      = @company.name
    %p
      %strong Adresse:
      = @company.adresse
    %p
      %strong Ville:
      = @company.city
    %p
      %strong Code Postal:
      = @company.cp


    = link_to 'Edit', edit_company_path(@company)
    = link_to 'Back', companies_path

  .col-md-8
    .page-header
      %h1 Soirée(s)
    %table.table
      %thead
        %tr
          %th Nom de la soirée
          %th date de départ
          %th date de fin
          %th etat
          %th Action

      %tbody
        - @evenings.each do |evening|
          %tr
            %td= evening.title
            %td= evening.date_start.strftime("%d/%m/%Y")
            %td= evening.date_end.strftime("%d/%m/%Y")
            - if evening.date_start.strftime("%d/%m/%Y") == DateTime.now.to_date.strftime("%d/%m/%Y")
              %td
                .btn.btn-xs.btn-success en cour
            - elsif DateTime.now.to_date > evening.date_end
              %td
                .btn.btn-xs.btn-danger Terminé
            - else
              %td
                .btn.btn-xs.btn-primary Bientôt
            %td
              = link_to 'Show', company_evening_path(evening.company_id,evening), class:"btn btn-primary", role:"button"
              = link_to 'Destroy',company_evening_path(evening.company_id,evening), data: {:confirm => 'Are you sure?'}, :method => :delete, class:"btn alert-danger"