config/routes.rb
Partynight::Application.routes.draw do

  devise_for :users
  devise_for :admins

  root "pages#index"
  resources :webservices
  resources :presentations
  

  match "/user/" => "users#index", via: [:get, :post]

  match "/api/companies/" => "webservices#title_companies", via: [:get, :post]

  match "/api/place/:name" => "webservices#company_nights", via: [:get, :post]
  match "/api/night/:id" => "webservices#night", via: [:get, :post]

  resources :companies do
    resources :evenings
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin)

    if admin
        can [:show,:edit,:update,:destroy ], Company, admin_id: admin.id
        can [:new, :index, :create], Company
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :evenings

  def all_evenings(id)
    @evenings = Evening.where(company_id: id)
    @evenings.to_json
  end

end

app/models/evening.rb
class Evening < ActiveRecord::Base

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  #upload de files
  has_attached_file :picture,
    :styles => {
      :medium => "429×500>"
    },
    :default_url => "/images/:style/missing.png",
    :url => "/picture/:class/:attachment/:id/:style/:basename.:extension",
    :path => ":rails_root/public/picture/:class/:attachment/:id/:style/:basename.:extension"


  belongs_to :company

  validates :title, presence: true
  validates :description, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
  # paperclip
  validates_attachment_content_type :picture, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


  # Evening.search({
  #   filter:{
  #     terms:{'propertie.title' => ["test","test1"]}
  #   }
  # })
end

app/models/news.rb
class News < ActiveRecord::Base

	validates :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  skip_before_filter  :protect_from_forgery
  # with: :exception


  rescue_from CanCan::AccessDenied do |exception|
    Rails.logger.debug "Access denied on #{exception.action} #{exception.subject.inspect}"

  end
  def current_ability
    @current_ability ||= Ability.new(current_admin)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :set_company, except: [:index, :new, :create, :nightIndex]
  #only: [:show, :edit, :update, :destroy]
  authorize_resource

  def index
    @companies = Company.where(admin_id: current_admin)
    @companie_name = Company.select(:name_company).where(admin_id: current_admin).distinct

    
    # @articles = Evening.search('Hip-Hop').records

  end

  def show
    @evenings = @company.evenings
  end

  def new
    @company = Company.new
  end


  def edit
  end


  def create
    @company = Company.new(company_params)

    @company.admin_id = current_admin.id
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private

    def set_company
      @company = Company.find(params[:id])
    end


    def company_params
      params.require(:company).permit(:name, :adresse, :city, :cp, :admin_id, :name_company)
    end

end

app/controllers/evenings_controller.rb
class EveningsController < ApplicationController

  before_filter :set_resources

  def index

  end
  def new
    @evening = Evening.new
  end

  def create
    @evening = Evening.new(evening_param)
    @evening.company_id = @company.id
    if @evening.save
      redirect_to  @company, flash:{ success: "La soirée #{@evening.title} à bien été crée"}
    else
      flash.now[:error]= "Certain champs n'ont pas été corectement remplir"
      render "new"

    end
  end
  def edit
  end
  def update
    if @evening.update(evening_param)
      redirect_to  @company, flash:{ success: "La soirée #{@evening.title} à bien été crée"}
    else
      flash.now[:error]= "Certain champs n'ont pas été corectement remplir"
      render "edit"
    end
  end

  def destroy
    @evening.destroy
    redirect_to @company, flash:{ success: "Soirée supprimer"}
  end

  private
  def set_resources
    @company = Company.find(params[:company_id])
    authorize! :destroy, @company
    @evening = Evening.find(params[:id]) if params[:id]
  end
  def evening_param
      params.require(:evening).permit(:title, :nb_get_in, :description, :price, :company_id, :date_start, :date_end, :picture)
  end
end

app/controllers/new_controller.rb
class NewsController < ApllicationController
	def new
		@new = New.new
	end

	def create
		@new = New.new(new_param)

		@new.save
	end

	def new_param
			params.require(:new).permit(:email)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to :controller =>"users", :action =>"index"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@evenings = Evening.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
    case type
    when :notice then "alert alert-info"
    when :success then "alert alert-success"
    when :error then "alert alert-danger"
    when :alert then "alert alert-danger"
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/evenings_helper.rb
module EveningsHelper
end

app/helpers/news_helpers.rb
module NewsHelper

	def form_new

		simple_form_for(@new) do |f|
			f.input :email, label: 'votre email'
			f.input :submit
		end

	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/presentation_helper.rb
module PresentationHelper

	def form_new
		simple_form_for(@new) do |f|
			f.input :email, label: 'votre email'
		end
	end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/helpers/webservices_helper.rb
module WebservicesHelper
end

app/views/layouts/_admin.html.haml
.navbar.navbar-inverse.navbar-fixed-top
	.container
		.navbar-header
			%a.navbar-brand Partynight
		.collapse.navbar-collapse
			- if admin_signed_in?
				%ul.nav.navbar-nav
					%li.active
						= link_to "Magasin", companies_path

			%ul.nav.navbar-nav.navbar-right
				- if admin_signed_in? || user_signed_in?
					%li
						= link_to 'Se déconnecter', destroy_admin_session_path, method: :delete

			- if admin_signed_in? || user_signed_in?
				%ul.navbar-form.navbar-right
					%form
						%input{type:"text", placeholder:"Recherche", class:"form-control"}
						%input{ type:"submit", value:"Recherche", class:"btn btn-default btn-primary"}



.main-content
	.container
		- flash.each do |type, message|
			%div{class: flash_class(type)}
				= message
		= yield

app/views/layouts/_presentation.html.haml
.header-presentation
	%header
		.hand
		.content-title
			.title
				Partynight
			.introduction
				Vous ne savez pas quoi faire un vendredi soir et bien partynight est fait pour
			%a.download
				donwload
			.news
		.clear
.content-presentation
	.content-diapo
		.content-text
			.diapo-title
				Presentation de l'application
			.diapo-text
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum velit vitae nulla molestie eu commodo nulla dapibus.
				Donec id sollicitudin urna. Integer at dui ac leo fermentum varius eleifend ut libero. Mauris interdum velit vitae nulla molestie
				eu commodo nulla dapibus.

			.diapo-title
				OU manger
			.diapo-text
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum velit vitae nulla molestie eu commodo nulla dapibus.
				Donec id sollicitudin urna. Integer at dui ac leo fermentum varius eleifend ut libero. Mauris interdum velit vitae nulla molestie
				eu commodo nulla dapibus.

			.diapo-title
				Vous avertir du dernier metro
			.diapo-text
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris interdum velit vitae nulla molestie eu commodo nulla dapibus.
				Donec id sollicitudin urna. Integer at dui ac leo fermentum varius eleifend ut libero. Mauris interdum velit vitae nulla molestie
				eu commodo nulla dapibus.
.footer
	.copyright
		&copy; 2013 -
		=DateTime.now.strftime("%Y")
		%span Partynight

app/views/layouts/_user.html.haml
.content-user

	.menu
		.picture-content
			.picture
		.content-tab
			%a.tab.icon-dash
				dash
		.content-tab-logout
			=link_to "Deconnection",destroy_user_session_path, method: :delete  , class:"tab tab-logout icon-logout"

	.content-dashboard
		.header-dashboard
			%p= current_user.email

		= yield
	.clear

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}

    -# %meta http-equiv="X-UA_Compatible" content="IE=edge,chrome=1"
    -# %meta{http-equiv:"content-Language" content:"fr"}

    %title= yield(:title)

    = stylesheet_link_tag "screen"

    -if request.path_info == "/presentations"
      = stylesheet_link_tag "style-presentation"



    = csrf_meta_tags

  %body

    -if admin_signed_in?
      =render "layouts/admin"
    -elsif user_signed_in?
      =render "layouts/user"
    -elsif request.path_info == "/presentations"
      =render "layouts/presentation"
    -else
      =render "layouts/admin"

    = javascript_include_tag 'application'
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/angularjs/1.2.21/angular.min.js'
    = javascript_include_tag 'https://code.angularjs.org/1.2.21/angular-route.min.js'
    :javascript
      $(".alert").delay(1000).fadeOut();

app/views/pages/index.html.haml
.content
	.admin.box
		.header Entreprise

		.content-box
			%p
				Vous êtes un café ou un pub ou même une société qui organise une soirée
			%p.center
				=link_to "Vous connectez", new_admin_session_path, class:"btn btn-primary"
				=link_to "Vous inscrire", new_admin_registration_path, class:"btn btn-default "


	.user.box
		.header Client
		.content-box
			%p
				vous voulez être avertir ou être au courant des soirée dans votre ville
			%p.center
				=link_to "Vous connectez", new_user_session_path, class:"btn btn-primary"
				=link_to "Vous inscrire", new_user_registration_path, class:"btn btn-default"